DATABASE_URL = "https://boxievkoxapefinwzbej.supabase.co"
DATABASE_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJveGlldmtveGFwZWZpbnd6YmVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MjE0MzgsImV4cCI6MjA2OTE5NzQzOH0.9EWt7bK2PSn7NHAMCAwoBrbjDagw-GQF9pcDzA3CQn4"
api_prefix = "https://api.argios.net/api/forms"

[users]
RRZ = "$2b$12$co0yUty4uh9EFVIgFLuiNe33cvRMtugGnRW5SrxuMotj28OZoAwu."
Aude = "$2b$12$0.SixW5zp0qRvTEhayTUruLr6B5l2zZUeSz4.BliocK9JLUkNfLv2"
Pam = "$2b$12$PisBbYIxloFO7f6BtzRPVOUmFaeAgH1Vj6A7cl7/lgA6MTluO1dOK"
Julien = "$2b$12$0VRK.IEGptKiDQYNT5HUlulYVH0HbMWkxLBoD.DKL.eu3rZZRdbOe"
Vermich = "$2b$12$k94ha0dwK.AERMYUOdxaBOLoWfUl2zvDhuA/q7gPFbZRFFpk8ht8S"
Vigie = "$2b$12$lhNdovKnTmjUuM0sgcnoOeOtJmyqT4jxrN55ekHSpdqtpVV0WfbCK"

[roles]
RRZ = "Argios"
Aude = "Argios"
Pam = "Argios"
Julien = "Argios"
Vermich = "Argios"
Vigie = "Vigie"